services:
  identity-service:
    volumes:
      - ./identity-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload-dir /app --reload-dir /common-lib

  core-service:
    volumes:
      - ./core-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload-dir /app --reload-dir /common-lib

  attendance-service:
    volumes:
      - ./attendance-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload-dir /app --reload-dir /common-lib

  payroll-service:
    volumes:
      - ./payroll-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload-dir /app --reload-dir /common-lib

  permission-service:
    volumes:
      - ./permission-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload-dir /app --reload-dir /common-lib

  talent-service:
    volumes:
      - ./talent-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload-dir /app --reload-dir /common-lib

  platform-service:
    volumes:
      - ./platform-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload-dir /app --reload-dir /common-lib


  identity-worker:
    volumes:
      - ./identity-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib

  core-worker:
    volumes:
      - ./core-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib

  attendance-worker:
    volumes:
      - ./attendance-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib

  payroll-worker:
    volumes:
      - ./payroll-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib

  talent-worker:
    volumes:
      - ./talent-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib

  platform-worker:
    volumes:
      - ./platform-service:/app
      - ./common-lib:/common-lib
    environment:
      PYTHONPATH: /common-lib
